---
title: "Egzamin (pierwszy termin) - Wizualizacja danych - Zestaw 3"
lang: pl
output:
  pdf_document: default
---

*Zadanie 1 i 2 po 15 pkt. Zadanie 3 - 20 pkt. *

*Punktacja: 46-50 pkt - bdb(5,0); 41-45 pkt - db+(4,5); 36-40 pkt - db(4,0); 31-35 pkt - dst+(3,5); 26-30 pkt - dst(3,0); 0-25 pkt - ndst (2,0).*  


Zad.1. Odwzoruj wykres znajdujący się w pliku graficznym 3.png znajdującym się folderze. Odcienie kolorów mogą się różnić, jednak główne barwy muszą być zachowane.
Zapisz powstały wykres w formacie jpg.

Zad.2. W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku produkcja3.xlsx jako ramkę danych (Data Frame),
* stwórz wykres punktowy prezentujący dane zawarte w ramce danych (wszystkie dane) - ustal kolor i wielkość (powierzchnię, średnicę) markera (znacznika) na inne wartości niż domyślne
* umieść aktualną godzinę (może być jako ciąg znaków na sztywno) w prawym dolnym rogu wykresu.

Wykres powinien być estetyczny i podpisany. Im więcej - tym lepiej.

Zapisz wykres w formacie png za pomocą kodu.

Zad.3. W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku sport3.csv,
* uporządkuj dane tak, aby dane liczbowe były zgodne z koncepcją "czystych danych" (w kolumnach)
* stwórz dwie ramki danych dotyczące oddzielne danych dotyczących kobiet i mężczyzn - na podstawie wyodrębnionych danych stwórz dwa wykres kołowe na jednym rysunku
* Wykres powinien być estetyczny i podpisany. Im więcej - tym lepiej.

Zapisz wykres w formacie pdf za pomocą kodu.
